org: millsp
app: prisma-serverless-stack
service: prisma-serverless-stack

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

custom:
  bundle:
    forceExclude:
      - "_http_common"
    copyFiles:
      - from: 'node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'
        to: 'node_modules/.prisma/client/query-engine-rhel-openssl-1.0.x'
      - from: 'node_modules/.prisma/client/schema.prisma'
        to: 'node_modules/.prisma/client/schema.prisma'
    packager: yarn
